spring:
  datasource:
    #    url: jdbc:h2:tcp://localhost/E:/h2-2019-10-14/h2/bin/mydb  # 配置h2数据库的连接地址
    url: jdbc:h2:mem:dbtest  # 配置h2数据库的连接地址
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      platform: h2
logging:
  level:
    root: debug